language: php

php:
  - nightly

sudo: false

install:
  - composer install
  - ./vendor/bin/codecept build
  - php vendor/bin/hyper-run tests/assets/www &

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

script:
  - php vendor/bin/codecept run unit --coverage --coverage-xml

branches:
  only:
    - master

after_script:
  - travis_retry php vendor/bin/coveralls
